# Generated by Django 2.1.1 on 2018-09-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180921_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ES', 'Especial'), ('PO', 'Potencial'), ('NO', 'Normal'), ('IN', 'Inactivo')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
