# Generated by Django 2.1.1 on 2018-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180922_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ES', 'Especial'), ('PO', 'Potencial'), ('NO', 'Normal'), ('IN', 'Inactivo')], default='NO', max_length=2, verbose_name='Status'),
        ),
    ]
